version: '2.2'
services:
  root:
    environment:
      - CFSSL_CSR=csr_root_ca.json
      - CFSSL_CONFIG=ca_root_config.json
      - DB_DISABLED=1
    volumes:
      - "root:/etc/cfssl"
  intermediate:
    depends_on:
      - root
    ports:
      - "8880:80"
    environment:
      - CFSSL_CSR=csr_intermediate_ca.json
      - CFSSL_CONFIG=ca_intermediate_config.json
      - CA_ROOT_URI=http://root
      - DB_DISABLED=1
    volumes:
      - "intermediate:/etc/cfssl"
volumes:
  root:
  intermediate: